minikube
Pods
6 items
Namespace: jupyterhub
Search Pods...
continuous-image-puller-h9xmt
jupyterhub
1
DaemonSet
minikube
BestEffort
23h
Running
hub-8f459c744-8bl9x
jupyterhub
0
ReplicaSet
minikube
BestEffort
11s
Running
jupyter-radoslawszmit
jupyterhub
1
minikube
Burstable
6s
Running
proxy-8675959d76-294lx
jupyterhub
1
ReplicaSet
minikube
BestEffort
23h
Running
user-scheduler-645b67778f-2x7qr
jupyterhub
1
ReplicaSet
minikube
BestEffort
23h
Running
user-scheduler-645b67778f-9xdr4
jupyterhub
1
ReplicaSet
minikube
BestEffort
23h
Running
Namespace
jupyterhub
Pod
jupyter-radoslawszmit
Container
notebook
Search...
WARNING: using start-singleuser.sh instead of start-notebook.sh to start a server associated with JupyterHub.
Entered start.sh with args: jupyterhub-singleuser --ip=0.0.0.0
Updated the jovyan user:
- username: jovyan       -> radoslawszmit
- home dir: /home/jovyan -> /home/radoslawszmit
Update radoslawszmit's UID:GID to 500:100
Changing working directory to /home/radoslawszmit/
Ensuring /home/radoslawszmit is owned by 500:100 
Granting radoslawszmit passwordless sudo rights!
Running as radoslawszmit: jupyterhub-singleuser --ip=0.0.0.0
[I 2022-03-14 11:01:38.637 SingleUserLabApp mixins:615] Starting jupyterhub single-user server version 2.1.1
[I 2022-03-14 11:01:38.637 SingleUserLabApp mixins:629] Extending jupyterlab.labhubapp.SingleUserLabApp from jupyterlab 3.2.9
[I 2022-03-14 11:01:38.637 SingleUserLabApp mixins:629] Extending jupyter_server.serverapp.ServerApp from jupyter_server 1.13.5
[W 2022-03-14 11:01:38.651 SingleUserLabApp configurable:193] Config option `open_browser` not recognized by `SingleUserLabApp`.  Did you mean `browser`?
[W 2022-03-14 11:01:38.664 SingleUserLabApp configurable:193] Config option `open_browser` not recognized by `SingleUserLabApp`.  Did you mean `browser`?
[I 2022-03-14 11:01:38.664 SingleUserLabApp manager:345] jupyterlab | extension was successfully linked.
[W 2022-03-14 11:01:38.667 NotebookApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-03-14 11:01:38.667 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-03-14 11:01:38.667 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-03-14 11:01:38.672 SingleUserLabApp configurable:193] Config option `open_browser` not recognized by `SingleUserLabApp`.  Did you mean `browser`?
/opt/conda/lib/python3.9/site-packages/IPython/paths.py:63: UserWarning: IPython dir '/home/radoslawszmit/.ipython' is not a writable location, using a temp directory.
  warn("IPython dir '{0}' is not a writable location,"
[I 2022-03-14 11:01:38.804 SingleUserLabApp manager:345] nbclassic | extension was successfully linked.
/opt/conda/lib/python3.9/site-packages/IPython/paths.py:63: UserWarning: IPython dir '/home/radoslawszmit/.ipython' is not a writable location, using a temp directory.
  warn("IPython dir '{0}' is not a writable location,"
[I 2022-03-14 11:01:38.823 SingleUserLabApp manager:367] nbclassic | extension was successfully loaded.
[I 2022-03-14 11:01:38.824 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.9/site-packages/jupyterlab
[I 2022-03-14 11:01:38.824 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2022-03-14 11:01:38.827 SingleUserLabApp manager:367] jupyterlab | extension was successfully loaded.
[I 2022-03-14 11:01:38.827 SingleUserLabApp mixins:641] Starting jupyterhub-singleuser server version 2.1.1
[W 2022-03-14 11:01:38.830 SingleUserLabApp _version:68] jupyterhub version 2.2.0 != jupyterhub-singleuser version 2.1.1. This could cause failure to authenticate and result in redirect loops!
[I 2022-03-14 11:01:38.830 SingleUserLabApp serverapp:2607] Serving notebooks from local directory: /home/radoslawszmit
[I 2022-03-14 11:01:38.830 SingleUserLabApp serverapp:2607] Jupyter Server 1.13.5 is running at:
[I 2022-03-14 11:01:38.830 SingleUserLabApp serverapp:2607] http://jupyter-radoslawszmit:8888/user/radoslawszmit/lab
[I 2022-03-14 11:01:38.830 SingleUserLabApp serverapp:2607]  or http://127.0.0.1:8888/user/radoslawszmit/lab
[I 2022-03-14 11:01:38.830 SingleUserLabApp serverapp:2608] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[E 2022-03-14 11:01:38.830 SingleUserLabApp serverapp:2444] Failed to write server-info to /home/radoslawszmit/.local/share/jupyter/runtime/jpserver-39.json: [Errno 13] Permission denied: '/home/radoslawszmit/.local/share/jupyter/runtime/jpserver-39.json'
Traceback (most recent call last):
  File "/opt/conda/bin/jupyterhub-singleuser", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/jupyterhub/singleuser/app.py", line 66, in main
    return SingleUserLabApp.launch_instance()
  File "/opt/conda/lib/python3.9/site-packages/jupyter_core/application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/opt/conda/lib/python3.9/site-packages/jupyterhub/singleuser/mixins.py", line 645, in start
Logs from 14.03.2022, 12:01:37
Show timestamps
Show previous terminated container
